### ISSUE TITLE
Top logo not loading on vanilla vue app

### ISSUE THREAD

**Issue by juan-carvajal** [kdydesign/vue-electron#2]
Hi, I cloned the template using vue/cli , installed everything, but the top logo is not found by webpack, is this an issue of configuration or am I doing something wrong? Shouldn't this work out of the box? I am attaching a screenshot of the issue.

I am using plain vue, no quasar or vuetify.

![image](https://user-images.githubusercontent.com/39658930/86073283-0e172c00-ba49-11ea-9bf0-c1bf07ee15e3.png)

**Comment by juan-carvajal** [comment]
Also, I am running windows

**Comment by Metainy** [comment]
This worked for me. Inside `.electron-vue\webpack.renderer.config.js` set `esModule: false`
```js
{
  test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
  use: {
    loader: 'url-loader',
    query: {
      limit: 10000,
      esModule: false,
      name: 'imgs/[name]--[folder].[ext]'
    }
  }
}
```
